version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  roscore:
    build:
        dockerfile: ./Dockerfile
    container_name: roscore
    depends_on:
      - mongodb
    ports:
      - "11411:11411"
      - "3636:3636"
      - "9090:9090"
    tty: true
    stdin_open: true
  nodered:
    build:
      context: .
      dockerfile: Dockerfile_Nodered
    container_name: nodered
    volumes:
      - ./flows:/data
    depends_on:
      - roscore
    environment:
      - ROS_MASTER_URI=http://roscore:11311
      - FLOWS=/data/flows.json
    ports:
      - "1880:1880"