version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/Fahim/Documents/rosserial-tcp-server-docker/mongo_data:/data/db
  roscore:
    build:
        dockerfile: ./Dockerfile
    container_name: roscore
    depends_on:
      - mongodb
    ports:
      - "11411:11411"
      - "3636:3636"
      - "9090:9090"
    tty: true
    stdin_open: true